version: 2.1

shared: &shared
  steps:
    - checkout
    - run:
        name: Install Python deps in a venv
        command: |
          sudo pip install --upgrade pip
          pip install -r ext/requirements-dev.txt
    - run:
        name: Running tests
        command: |
          coverage run -m unittest tests/test_simpleplots.py
    - run: |
        if [ $UPLOAD_COV ]; then
          codecov
        fi

jobs:
  py37:
    <<: *shared
    docker:
      - image: circleci/python:3.7

  py38:
    <<: *shared
    docker:
      - image: circleci/python:3.8
        environment:
          UPLOAD_COV: "true"

workflows:
  version: 2.1
  main:
    jobs:
      - py37
      - py38
